import '../application/meal_calorie_estimator.dart';
import '../gen/app_localizations.dart';

String mealFoodLabel(AppLocalizations l10n, String foodId) {
  return switch (foodId) {
    'chickenBreast' => l10n.mealDishChickenBreast,
    'eggs' => l10n.mealDishEggs,
    'tofu' => l10n.mealDishTofu,
    'grilledFish' => l10n.mealDishGrilledFish,
    'salmon' => l10n.mealDishSalmon,
    'bulgogi' => l10n.mealDishBulgogi,
    'kimchiStew' => l10n.mealDishKimchiStew,
    'doenjangStew' => l10n.mealDishDoenjangStew,
    'friedChicken' => l10n.mealDishFriedChicken,
    'chickenSalad' => l10n.mealDishChickenSalad,
    'ramen' => l10n.mealDishRamen,
    'sandwich' => l10n.mealDishSandwich,
    'bibimbap' => l10n.mealFoodBibimbap,
    'friedRice' => l10n.mealFoodFriedRice,
    'gimbap' => l10n.mealFoodGimbap,
    'curryRice' => l10n.mealFoodCurryRice,
    'porkCutlet' => l10n.mealFoodPorkCutlet,
    'jajangmyeon' => l10n.mealFoodJajangmyeon,
    'jjampong' => l10n.mealFoodJjampong,
    'tteokbokki' => l10n.mealFoodTteokbokki,
    'pasta' => l10n.mealFoodPasta,
    'hamburger' => l10n.mealFoodHamburger,
    'pizza' => l10n.mealFoodPizza,
    'porkBelly' => l10n.mealFoodPorkBelly,
    'jeyukBokkeum' => l10n.mealFoodJeyukBokkeum,
    'beefSteak' => l10n.mealFoodBeefSteak,
    'dakgalbi' => l10n.mealFoodDakgalbi,
    'omurice' => l10n.mealFoodOmurice,
    'udon' => l10n.mealFoodUdon,
    'coldNoodles' => l10n.mealFoodColdNoodles,
    'soybeanNoodles' => l10n.mealFoodSoybeanNoodles,
    'dumplingSoup' => l10n.mealFoodDumplingSoup,
    'samgyetang' => l10n.mealFoodSamgyetang,
    'kimchi' => l10n.mealFoodKimchi,
    'pickledRadish' => l10n.mealFoodPickledRadish,
    'seasonedBeanSprouts' => l10n.mealFoodSeasonedBeanSprouts,
    'spinachNamul' => l10n.mealFoodSpinachNamul,
    'seaweedSalad' => l10n.mealFoodSeaweedSalad,
    'lettuce' => l10n.mealFoodLettuce,
    'cucumber' => l10n.mealFoodCucumber,
    'tomato' => l10n.mealFoodTomato,
    'avocado' => l10n.mealFoodAvocado,
    'broccoli' => l10n.mealFoodBroccoli,
    'sweetPotato' => l10n.mealFoodSweetPotato,
    'potato' => l10n.mealFoodPotato,
    'corn' => l10n.mealFoodCorn,
    'boiledEgg' => l10n.mealFoodBoiledEgg,
    'friedEgg' => l10n.mealFoodFriedEgg,
    'omelet' => l10n.mealFoodOmelet,
    'cheese' => l10n.mealFoodCheese,
    'tunaCan' => l10n.mealFoodTunaCan,
    'ham' => l10n.mealFoodHam,
    'sausage' => l10n.mealFoodSausage,
    'bacon' => l10n.mealFoodBacon,
    'mackerel' => l10n.mealFoodMackerel,
    'shrimp' => l10n.mealFoodShrimp,
    'squid' => l10n.mealFoodSquid,
    'beans' => l10n.mealFoodBeans,
    'chickpeas' => l10n.mealFoodChickpeas,
    'lentils' => l10n.mealFoodLentils,
    'seaweedSoup' => l10n.mealFoodSeaweedSoup,
    'beefSoup' => l10n.mealFoodBeefSoup,
    'eggSoup' => l10n.mealFoodEggSoup,
    'tofuSoup' => l10n.mealFoodTofuSoup,
    'vegetableSoup' => l10n.mealFoodVegetableSoup,
    'misoSoup' => l10n.mealFoodMisoSoup,
    'chickenSoup' => l10n.mealFoodChickenSoup,
    'dumplings' => l10n.mealFoodDumplings,
    'friedSnack' => l10n.mealFoodFriedSnack,
    'frenchFries' => l10n.mealFoodFrenchFries,
    'riceCake' => l10n.mealFoodRiceCake,
    'breadSlice' => l10n.mealFoodBreadSlice,
    'toast' => l10n.mealFoodToast,
    'oatmeal' => l10n.mealFoodOatmeal,
    'cereal' => l10n.mealFoodCereal,
    'granola' => l10n.mealFoodGranola,
    'mixedNuts' => l10n.mealFoodMixedNuts,
    'almonds' => l10n.mealFoodAlmonds,
    'iceCream' => l10n.mealFoodIceCream,
    'chocolate' => l10n.mealFoodChocolate,
    'cookie' => l10n.mealFoodCookie,
    'cake' => l10n.mealFoodCake,
    'yogurt' => l10n.mealFoodYogurt,
    'greekYogurt' => l10n.mealFoodGreekYogurt,
    'proteinShake' => l10n.mealFoodProteinShake,
    'wheyProtein' => l10n.mealFoodWheyProtein,
    'milk' => l10n.mealFoodMilk,
    'soyMilk' => l10n.mealFoodSoyMilk,
    'juice' => l10n.mealFoodJuice,
    'sportsDrink' => l10n.mealFoodSportsDrink,
    'coffeeLatte' => l10n.mealFoodCoffeeLatte,
    'americano' => l10n.mealFoodAmericano,
    'cola' => l10n.mealFoodCola,
    'water' => l10n.mealFoodWater,
    'banana' => l10n.mealFoodBanana,
    'apple' => l10n.mealFoodApple,
    'orange' => l10n.mealFoodOrange,
    'grapes' => l10n.mealFoodGrapes,
    'strawberries' => l10n.mealFoodStrawberries,
    'blueberries' => l10n.mealFoodBlueberries,
    _ => foodId,
  };
}

String mealFoodCategoryLabel(
  AppLocalizations l10n,
  MealFoodCategory category,
) {
  return switch (category) {
    MealFoodCategory.main => l10n.mealFoodCategoryMain,
    MealFoodCategory.protein => l10n.mealFoodCategoryProtein,
    MealFoodCategory.side => l10n.mealFoodCategorySide,
    MealFoodCategory.soup => l10n.mealFoodCategorySoup,
    MealFoodCategory.carb => l10n.mealFoodCategoryCarb,
    MealFoodCategory.fruit => l10n.mealFoodCategoryFruit,
    MealFoodCategory.snack => l10n.mealFoodCategorySnack,
    MealFoodCategory.drink => l10n.mealFoodCategoryDrink,
  };
}
