class WorldCupRosterPool {
  final String formation;
  final List<String> goalkeepers;
  final List<String> defenders;
  final List<String> midfielders;
  final List<String> forwards;

  const WorldCupRosterPool({
    required this.formation,
    required this.goalkeepers,
    required this.defenders,
    required this.midfielders,
    required this.forwards,
  });
}

WorldCupRosterPool? worldCupRosterPoolForTeam(String team) {
  return worldCupRosterPools[team.trim()];
}

const Map<String, WorldCupRosterPool>
worldCupRosterPools = <String, WorldCupRosterPool>{
  'Algeria': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Oussama Benbot', 'Melvin Masstil', 'Luca Zidane'],
    defenders: [
      'Achraf Abada',
      'Rayan Ait-Nouri',
      'Zinedine Belaid',
      'Rafik Belghali',
      'Ramy Bensebaini',
      'Samir Chergui',
      'Jaouen Hadjam',
      'Aissa Mandi',
      'Mohamed Amine Tougai',
    ],
    midfielders: [
      'Houssem Aouar',
      'Nabil Bentaleb',
      'Hicham Boudaoui',
      'Fares Chaibi',
      'Ibrahim Maza',
      'Yassine Titraoui',
      'Ramiz Zerrouki',
    ],
    forwards: [
      'Mohamed Amine Amoura',
      'Nadir Benbouali',
      'Adil Boulbina',
      'Fares Ghedjemis',
      'Amine Gouiri',
      'Riyad Mahrez',
      'Anis Hadj Moussa',
    ],
  ),
  'Argentina': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Juan Musso', 'Geronimo Rulli', 'Emiliano Martinez'],
    defenders: [
      'Leonardo Balerdi',
      'Nicolas Tagliafico',
      'Gonzalo Montiel',
      'Lisandro Martinez',
      'Cristian Romero',
      'Nicolas Otamendi',
      'Facundo Medina',
      'Nahuel Molina',
    ],
    midfielders: [
      'Leandro Paredes',
      'Rodrigo de Paul',
      'Valentin Barco',
      'Giovani lo Celso',
      'Ezequiel Palacios',
      'Alexis Mac Allister',
      'Enzo Fernandez',
    ],
    forwards: [
      'Julian Alvarez',
      'Lionel Messi',
      'Nicolas Gonzalez',
      'Thiago Almada',
      'Giuliano Simeone',
      'Nico Paz',
      'Jose Manuel Lopez',
      'Lautaro Martinez',
    ],
  ),
  'Australia': WorldCupRosterPool(
    formation: '5-4-1',
    goalkeepers: ['Mat Ryan', 'Paul Izzo', 'Patrick Beach'],
    defenders: [
      'Aziz Behich',
      'Jordan Bos',
      'Cameron Burgess',
      'Alessandro Circati',
      'Milos Degenek',
      'Jason Geria',
      'Lucas Herrington',
      'Jacob Italiano',
      'Harry Souttar',
      'Kai Trewin',
    ],
    midfielders: [
      'Cammy Devlin',
      'Ajdin Hrustic',
      'Jackson Irvine',
      'Connor Metcalfe',
      'Paul Okon-Engstler',
      'Aiden O\'Neill',
    ],
    forwards: [
      'Nestory Irankunda',
      'Mathew Leckie',
      'Awer Mabil',
      'Mohamed Toure',
      'Nishan Velupilly',
      'Cristian Volpato',
      'Tete Yengi',
    ],
  ),
  'Austria': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Patrick Pentz', 'Alexander Schlager', 'Florian Wiegele'],
    defenders: [
      'David Affengruber',
      'David Alaba',
      'Kevin Danso',
      'Marco Friedl',
      'Philipp Lienhart',
      'Dejan Ljubicic',
      'Phillipp Mwene',
      'Stefan Posch',
      'Alexander Prass',
      'Michael Svoboda',
    ],
    midfielders: [
      'Carney Chukwuemeka',
      'Florian Grillitsch',
      'Konrad Laimer',
      'Marcel Sabitzer',
      'Xaver Schlager',
      'Romano Schmid',
      'Alessandro Schopf',
      'Nicolas Seiwald',
      'Paul Wanner',
      'Patrick Wimmer',
    ],
    forwards: ['Marko Arnautovic', 'Michael Gregoritsch', 'Sasa Kalajdzic'],
  ),
  'Belgium': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Thibaut Courtois', 'Senne Lammens', 'Mike Penders'],
    defenders: [
      'Timothy Castagne',
      'Zeno Debast',
      'Maxim De Cuyper',
      'Koni De Winter',
      'Brandon Mechele',
      'Thomas Meunier',
      'Nathan Ngoy',
      'Joaquin Seys',
      'Arthur Theate',
    ],
    midfielders: [
      'Kevin De Bruyne',
      'Amadou Onana',
      'Nicolas Raskin',
      'Youri Tielemans',
      'Hans Vanaken',
      'Axel Witsel',
    ],
    forwards: [
      'Charles De Ketelaere',
      'Jeremy Doku',
      'Matias Fernandez-Pardo',
      'Romelu Lukaku',
      'Dodi Lukebakio',
      'Diego Moreira',
      'Alexis Saelemaekers',
      'Leandro Trossard',
    ],
  ),
  'Bosnia and Herzegovina': WorldCupRosterPool(
    formation: '4-4-2',
    goalkeepers: ['Nikola Vasilj', 'Martin Zlomislic', 'Mladen Jurkas'],
    defenders: [
      'Sead Kolasinac',
      'Amar Dedic',
      'Nihad Mujakic',
      'Nikola Katic',
      'Tarik Muharemovic',
      'Stjepan Radeljic',
      'Dennis Hadzikadunic',
      'Nidal Celik',
    ],
    midfielders: [
      'Amir Hadziahmetovic',
      'Ivan Sunjic',
      'Ivan Basic',
      'Dzenis Burnic',
      'Ermin Mahmic',
      'Benjamin Tahirovic',
      'Amar Memic',
      'Armin Gigovic',
      'Kerim Alajbegovic',
      'Esmir Bajraktarevic',
    ],
    forwards: [
      'Ermedin Demirovic',
      'Jovo Lukic',
      'Samed Bazdar',
      'Haris Tabakovic',
      'Edin Dzeko',
    ],
  ),
  'Brazil': WorldCupRosterPool(
    formation: '4-2-4',
    goalkeepers: ['Alisson', 'Ederson', 'Weverton'],
    defenders: [
      'Alex Sandro',
      'Bremer',
      'Danilo',
      'Douglas Santos',
      'Gabriel Magalhaes',
      'Ibanez',
      'Leo Pereira',
      'Marquinhos',
      'Wesley',
    ],
    midfielders: [
      'Bruno Guimaraes',
      'Casemiro',
      'Danilo Santos',
      'Fabinho',
      'Lucas Paqueta',
    ],
    forwards: [
      'Endrick',
      'Gabriel Martinelli',
      'Igor Thiago',
      'Luiz Henrique',
      'Matheus Cunha',
      'Neymar',
      'Raphinha',
      'Rayan',
      'Vinicius Jr',
    ],
  ),
  'Canada': WorldCupRosterPool(
    formation: '4-4-2',
    goalkeepers: ['Dayne St Clair', 'Maxime Crepeau', 'Owen Goodman'],
    defenders: [
      'Alistair Johnston',
      'Derek Cornelius',
      'Richie Laryea',
      'Niko Sigur',
      'Joel Waterman',
      'Luc de Fougerolles',
      'Moise Bombito',
      'Alphonso Davies',
      'Alfie Jones',
    ],
    midfielders: [
      'Stephen Eustaquio',
      'Ismael Kone',
      'Tajon Buchanan',
      'Mathieu Choiniere',
      'Ali Ahmed',
      'Nathan Saliba',
      'Liam Millar',
      'Jacob Shaffelburg',
      'Jonathan Osorio',
    ],
    forwards: [
      'Jonathan David',
      'Cyle Larin',
      'Tani Oluwaseyi',
      'Promise David',
    ],
  ),
  'Cape Verde': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Vozinha', 'Marcio Rosa', 'CJ dos Santos'],
    defenders: [
      'Stopira',
      'Roberto Lopes',
      'Joao Paulo',
      'Diney',
      'Logan Costa',
      'Steven Moreira',
      'Wagner Pina',
      'Sidny Lopes Cabral',
      'Kelvin Pires',
    ],
    midfielders: [
      'Jamiro Monteiro',
      'Kevin Pina',
      'Deroy Duarte',
      'Telmo Arcanjo',
      'Laros Duarte',
      'Yannick Semedo',
    ],
    forwards: [
      'Ryan Mendes',
      'Garry Rodrigues',
      'Willy Semedo',
      'Jovane Cabral',
      'Gilson Tavares',
      'Dailon Livramento',
      'Helio Varela',
      'Nuno da Costa',
    ],
  ),
  'Colombia': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Camilo Vargas', 'Alvaro Montero', 'David Ospina'],
    defenders: [
      'Davinson Sanchez',
      'Jhon Lucumi',
      'Yerry Mina',
      'Willer Ditta',
      'Daniel Munoz',
      'Santiago Arias',
      'Johan Mojica',
      'Deiver Machado',
    ],
    midfielders: [
      'Richard Rios',
      'Jefferson Lerma',
      'Kevin Castano',
      'Juan Camilo Portilla',
      'Gustavo Puerta',
      'Jhon Arias',
      'Jorge Carrascal',
      'Juan Fernando Quintero',
      'James Rodriguez',
      'Jaminton Campaz',
    ],
    forwards: [
      'Juan Camilo Hernandez',
      'Luis Diaz',
      'Luis Suarez',
      'Carlos Andres Gomez',
      'Jhon Cordoba',
    ],
  ),
  'Congo DR': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Matthieu Epolo', 'Timothy Fayulu', 'Lionel Mpasi'],
    defenders: [
      'Dylan Batubinsika',
      'Gedeon Kalulu',
      'Steve Kapuadi',
      'Joris Kayembe',
      'Arthur Masuaku',
      'Chancel Mbemba',
      'Axel Tuanzebe',
      'Aaron Wan-Bissaka',
    ],
    midfielders: [
      'Theo Bongonda',
      'Brian Cipenga',
      'Elia Meshack',
      'Gael Kakuta',
      'Edo Kayembe',
      'Nathanael Mbuku',
      'Samuel Moutoussamy',
      'Ngalayel Mukau',
      'Charles Pickel',
      'Noah Sadiki',
      'Aaron Tshibola',
    ],
    forwards: ['Cedric Bakambu', 'Simon Banza', 'Fiston Mayele', 'Yoane Wissa'],
  ),
  'Croatia': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Dominik Livakovic', 'Dominik Kotarski', 'Ivor Pandur'],
    defenders: [
      'Josko Gvardiol',
      'Duje Caleta-Car',
      'Josip Sutalo',
      'Josip Stanisic',
      'Marin Pongracic',
      'Martin Erlic',
      'Luka Vuskovic',
    ],
    midfielders: [
      'Luka Modric',
      'Mateo Kovacic',
      'Mario Pasalic',
      'Nikola Vlasic',
      'Luka Sucic',
      'Martin Baturina',
      'Kristijan Jakic',
      'Petar Sucic',
      'Nikola Moro',
      'Toni Fruk',
    ],
    forwards: [
      'Ivan Perisic',
      'Andrej Kramaric',
      'Ante Budimir',
      'Marco Pasalic',
      'Petar Musa',
      'Igor Matanovic',
    ],
  ),
  'Curacao': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Tyrick Bodak', 'Trevor Doornbusch', 'Eloy Room'],
    defenders: [
      'Riechedly Bazoer',
      'Joshua Brenet',
      'Roshon Van Eijma',
      'Sherel Floranus',
      'Deveron Fonville',
      'Jurien Gaari',
      'Armando Obispo',
      'Shurandy Sambo',
    ],
    midfielders: [
      'Juninho Bacuna',
      'Leandro Bacuna',
      'Livano Comenencia',
      'Kevin Felida',
      'Ar\'Jany Martha',
      'Tyrese Noslin',
      'Godfried Roemeratoe',
    ],
    forwards: [
      'Jeremy Antonisse',
      'Tahith Chong',
      'Kenji Gorre',
      'Sontje Hansen',
      'Gervane Kastaneer',
      'Brandley Kuwas',
      'Jurgen Locadia',
      'Jearl Margaritha',
    ],
  ),
  'Czechia': WorldCupRosterPool(
    formation: '3-4-3',
    goalkeepers: ['Lukas Hornicek', 'Matej Kovar', 'Jindrich Stanek'],
    defenders: [
      'Vladimir Coufal',
      'David Doudera',
      'Tomas Holes',
      'Robin Hranac',
      'Stepan Chaloupek',
      'David Jurasek',
      'Ladislav Krejci',
      'Jaroslav Zeleny',
      'David Zima',
    ],
    midfielders: [
      'Lukas Cerv',
      'Vladimir Darida',
      'Lukas Provod',
      'Michal Sadilek',
      'Hugo Sochurek',
      'Alexandr Sojka',
      'Tomas Soucek',
      'Pavel Sulc',
      'Denis Visinsky',
    ],
    forwards: [
      'Adam Hlozek',
      'Tomas Chory',
      'Mojmir Chytil',
      'Jan Kuchta',
      'Patrik Schick',
    ],
  ),
  'Ecuador': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Hernan Galindez', 'Moises Ramirez', 'Gonzalo Valle'],
    defenders: [
      'Piero Hincapie',
      'Willian Pacho',
      'Pervis Estupinan',
      'Felix Torres',
      'Joel Ordonez',
      'Jackson Porozo',
      'Angelo Preciado',
    ],
    midfielders: [
      'Moises Caicedo',
      'Alan Franco',
      'Kendry Paez',
      'Pedro Vite',
      'Jordy Alcivar',
      'Denil Castillo',
      'Yaimar Medina',
    ],
    forwards: [
      'Enner Valencia',
      'Kevin Rodriguez',
      'Jordy Caicedo',
      'Nilson Angulo',
      'Anthony Valencia',
      'Jeremy Arevalo',
    ],
  ),
  'Egypt': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: [
      'Mohamed El Shenawy',
      'Mostafa Shobeir',
      'El Mahdi Soliman',
      'Mohamed Alaa',
    ],
    defenders: [
      'Mohamed Hany',
      'Tarek Alaa',
      'Hamdy Fathy',
      'Rami Rabia',
      'Yasser Ibrahim',
      'Hossam Abdelmaguid',
      'Mohamed Abdelmonemn',
      'Ahmed Fatouh',
      'Karim Hafez',
    ],
    midfielders: [
      'Marwan Ateya',
      'Mohanad Lasheen',
      'Nabil Emad',
      'Mahmoud Saber',
      'Ahmed Zizo',
      'Emam Ashour',
      'Mostafa Ziko',
      'Mahmoud Trezeguet',
      'Ibrahim Adel',
      'Haissem Hassan',
    ],
    forwards: ['Omar Marmoush', 'Mohamed Salah', 'Hamza Abdelkarim'],
  ),
  'England': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Jordan Pickford', 'Dean Henderson', 'James Trafford'],
    defenders: [
      'Reece James',
      'Tino Livramento',
      'John Stones',
      'Marc Guehi',
      'Ezri Konsa',
      'Dan Burn',
      'Jarell Quansah',
      'Djed Spence',
      'Nico O\'Reilly',
    ],
    midfielders: [
      'Elliot Anderson',
      'Jordan Henderson',
      'Declan Rice',
      'Kobbie Mainoo',
      'Eberechi Eze',
      'Jude Bellingham',
      'Morgan Rogers',
    ],
    forwards: [
      'Bukayo Saka',
      'Noni Madueke',
      'Anthony Gordon',
      'Marcus Rashford',
      'Harry Kane',
      'Ollie Watkins',
      'Ivan Toney',
    ],
  ),
  'France': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Mike Maignan', 'Robin Risser', 'Brice Samba'],
    defenders: [
      'Lucas Digne',
      'Malo Gusto',
      'Lucas Hernandez',
      'Theo Hernandez',
      'Ibrahima Konate',
      'Maxence Lacroix',
      'Jules Kounde',
      'William Saliba',
      'Dayot Upamenaco',
    ],
    midfielders: [
      'N\'Golo Kante',
      'Manu Kone',
      'Adrien Rabiot',
      'Aurelien Tchouameni',
      'Warren Zaire-Emery',
    ],
    forwards: [
      'Maghnes Akliouche',
      'Bradley Barcola',
      'Rayan Cherki',
      'Ousmane Dembele',
      'Desire Doue',
      'Michael Olise',
      'Kylian Mbappe',
      'Jean-Phillipe Mateta',
      'Marcus Thuram',
    ],
  ),
  'Germany': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Oliver Baumann', 'Manuel Neuer', 'Alexander Nubel'],
    defenders: [
      'Joshua Kimmich',
      'Nico Schlotterbeck',
      'Nathaniel Brown',
      'David Raum',
      'Waldemar Anton',
      'Antonio Rudiger',
      'Malick Thiaw',
      'Jonathan Tah',
    ],
    midfielders: [
      'Jamal Musiala',
      'Jamie Leweling',
      'Aleksandar Pavlovic',
      'Nadiem Amiri',
      'Felix Nmecha',
      'Angelo Stiller',
      'Leon Goretzka',
      'Pascal Gross',
    ],
    forwards: [
      'Kai Havertz',
      'Deniz Undav',
      'Maximilian Beier',
      'Florian Wirtz',
      'Nick Woltemade',
      'Lennart Karl',
      'Leroy Sane',
    ],
  ),
  'Ghana': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Benjamin Asare', 'Lawrence Ati-Zigi', 'Joseph Anang'],
    defenders: [
      'Baba Abdul Rahman',
      'Gideon Mensah',
      'Marvin Senaya',
      'Alidu Seidu',
      'Abdul Mumin',
      'Jerome Opoku',
      'Jonas Adjetey',
      'Kojo Oppong Peprah',
      'Derrick Luckassen',
      'Elisha Owusu',
    ],
    midfielders: [
      'Thomas Partey',
      'Kwasi Sibo',
      'Augustine Boakye',
      'Caleb Yirenkyi',
      'Abdul Fatawu',
    ],
    forwards: [
      'Kamaldeen Sulemana',
      'Christopher Bonsu Baah',
      'Ernest Nuamah',
      'Antoine Semenyo',
      'Brandon Thomas-Asante',
      'Prince Kwabena Adu',
      'Inaki Williams',
      'Jordan Ayew',
    ],
  ),
  'Haiti': WorldCupRosterPool(
    formation: '4-4-2',
    goalkeepers: ['Johnny Placide', 'Alexandre Pierre', 'Josue Duverger'],
    defenders: [
      'Carlens Arcus',
      'Wilguens Pauguain',
      'Duke Lacroix',
      'Martin Experience',
      'Jean-Kevin Duverne',
      'Ricardo Ade',
      'Hannes Delcroix',
      'Keeto Thermoncy',
    ],
    midfielders: [
      'Leverton Pierre',
      'Carl-Fred Sainthe',
      'Jean-Jacques Danley',
      'Jean-Ricner Bellegarde',
      'Pierre Woodenski',
      'Dominique Simon',
    ],
    forwards: [
      'Louicius Deedson',
      'Ruben Providence',
      'Josue Casimir',
      'Derrick Etienne',
      'Wilson Isidor',
      'Duckens Nazon',
      'Frantzdy Pierrot',
      'Yassin Fortune',
      'Lenny Joseph',
    ],
  ),
  'Iran': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Alireza Beiranvand', 'Hossein Hosseini', 'Payam Niazmand'],
    defenders: [
      'Danial Eiri',
      'Ehsan Hajsafi',
      'Saleh Hardani',
      'Hossein Kanaani',
      'Shoja Khalilzadeh',
      'Milad Mohammadi',
      'Ali Nemati Omid Noorafkan',
      'Ramin Rezaeian',
    ],
    midfielders: [
      'Rouzbeh Cheshmi',
      'Saeid Ezatolahi',
      'Mehdi Ghaedi',
      'Saman Ghoddos',
      'Mohammad Ghorbani',
      'Alireza Jahanbakhsh',
      'Mohammad Mohebi',
      'Amir Mohammad Razzaghinia',
      'Mehdi Torabi',
      'Aria Yousefi',
    ],
    forwards: [
      'Ali Alipour',
      'Dennis Dargahi',
      'Amirhossein Hosseinzadeh',
      'Shahriyar Moghanlou',
      'Mehdi Taremi',
    ],
  ),
  'Iraq': WorldCupRosterPool(
    formation: '4-4-2',
    goalkeepers: ['Fahad Talib', 'Jalal Hassan', 'Ahmed Basil'],
    defenders: [
      'Hussein Ali',
      'Manaf Younis',
      'Ahmed Yahya',
      'Mustafa Saadoon',
      'Zaid Tahseen',
      'Rebin Sulaka',
      'Akam Hashim',
      'Merchas Doski',
      'Zaid Ismail',
      'Frans Putros',
    ],
    midfielders: [
      'Amir Al-Ammari',
      'Kevin Yakob',
      'Zidane Iqbal',
      'Aimar Sher',
      'Ibrahim Bayesh',
      'Ahmed Qasem',
      'Youssef Amyn',
      'Marko Farji',
    ],
    forwards: [
      'Ali Jassim',
      'Ali Al-Hamadi',
      'Ali Yousef',
      'Aymen Hussein',
      'Mohanad Ali',
    ],
  ),
  'Ivory Coast': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Yahia Fofana', 'Mohamed Kone', 'Alban Lafont'],
    defenders: [
      'Emmanuel Agbadou',
      'Christopher Operi',
      'Ousmane Diomande',
      'Guela Doue',
      'Ghislain Konan',
      'Odilon Kossonou',
      'Evan Ndicka',
      'Wilfried Singo',
    ],
    midfielders: [
      'Seko Fofana',
      'Parfait Guiagon',
      'Franck Kessie',
      'Christ Oulai',
      'Ibrahim Sangare',
      'Jean-Michael Seri',
    ],
    forwards: [
      'Simon Adingra',
      'Ange-Yoan Bonny',
      'Amad Diallo',
      'Oumar Diakite',
      'Yan Diomande',
      'Evann Guessand',
      'Nicolas Pepe',
      'Bazoumana Toure',
      'Elye Wahi',
    ],
  ),
  'Japan': WorldCupRosterPool(
    formation: '3-4-3',
    goalkeepers: ['Tomoki Hayakawa', 'Keisuke Osako', 'Zion Suzuki'],
    defenders: [
      'Yuto Nagatomo',
      'Shogo Taniguchi',
      'Ko Itakura',
      'Tsuyoshi Watanabe',
      'Takehiro Tomiyasu',
      'Hiroki Ito',
      'Ayumu Seko',
      'Yukinari Sugawara',
      'Junosuke Suzuki',
    ],
    midfielders: [
      'Wataru Endo',
      'Junya Ito',
      'Daichi Kamada',
      'Koki Ogawa',
      'Daizen Maeda',
      'Ritsu Doan',
      'Ao Tanaka',
      'Kaishu Sano',
      'Takefusa Kubo',
    ],
    forwards: [
      'Ayase Ueda',
      'Keito Nakamura',
      'Ito Suzuki',
      'Kento Shiode',
      'Keisuke Goto',
    ],
  ),
  'Jordan': WorldCupRosterPool(
    formation: '5-2-3',
    goalkeepers: [
      'Yazeed Abulaila',
      'Abdullah Al-Fakhouri',
      'Noor Bani Attiah',
    ],
    defenders: [
      'Abdallah Nasib',
      'Ehsan Haddad',
      'Saed Al-Rosan',
      'Saleem Obaid',
      'Yazan Al-Arab',
      'Mohammad Abualnadi',
      'Husam Abu Dahab',
      'Anas Banawi',
      'Mohannad Abu Taha',
      'Mohammad Abu Hasheesh',
      'Mohammad Abu Ghosh.',
    ],
    midfielders: [
      'Noor Al Rawabdeh',
      'Nizar Al Rashdan',
      'Ibrahim Saadeh',
      'Rajaei Ayed',
      'Mahmoud Al-Mardi',
      'Amer Jamous',
      'Mohammad Al-Dawoud',
    ],
    forwards: [
      'Mousa Al-Tamari',
      'Odeh Al-Fakhouri',
      'Mohammad Abu Zrayq',
      'Ali Azaizeh',
      'Ali Olwan',
    ],
  ),
  'Korea Republic': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Jo Hyeon-woo', 'Kim Seung-gyu', 'Song Bum-keun'],
    defenders: [
      'Kim Moon-hwan',
      'Kim Min-jae',
      'Kim Tae-hyon',
      'Park Jin-seob',
      'Seol Young-woo',
      'Jens Castrop',
      'Lee Ki-hyuk',
      'Lee Tae-seok',
      'Lee Han-beom',
      'Cho Wi-je',
    ],
    midfielders: [
      'Kim Jin-gyu',
      'Bae Jun-ho',
      'Paik Seung-ho',
      'Yang Hyun-jun',
      'Eom Ji-sung',
      'Lee Kang-in',
      'Lee Dong-gyeong',
      'Lee Jae-sung',
      'Hwang In-beom',
      'Hwang Hee-chan',
    ],
    forwards: ['Son Heung-min', 'Oh Hyeon-gyu', 'Cho Gue-sung'],
  ),
  'Mexico': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Raul Rangel', 'Guillermo Ochoa', 'Carlos Acevedo'],
    defenders: [
      'Jorge Sanchez',
      'Israel Reyes',
      'Cesar Montes',
      'Johan Vasquez',
      'Jesus Gallardo',
      'Mateo Chavez',
    ],
    midfielders: [
      'Erik Lira',
      'Orbelin Pineda',
      'Alvaro Fidalgo',
      'Roberto Alvarado',
      'Brian Gutierrez',
      'Luis Romo',
      'Edson Alvarez',
      'Obed Vargas',
      'Gilberto Mora',
      'Luis Chavez',
    ],
    forwards: [
      'Cesar Huerta',
      'Alexis Vega',
      'Julian Quinones',
      'Guillermo Martinez',
      'Armando Gonzalez',
      'Santiago Gimenez',
      'Raul Jimenez',
    ],
  ),
  'Morocco': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Yassine Bounou', 'Munir El Kajoui', 'Ahmed Reda Tagnaouti'],
    defenders: [
      'Nayef Aguerd',
      'Youssef Belammari',
      'Issa Diop',
      'Zakaria El Ouahdi',
      'Achraf Hakimi',
      'Redouane Halhal',
      'Noussair Mazraoui',
      'Chadi Riad',
      'Anass Salah-Eddine',
    ],
    midfielders: [
      'Sofyan Amrabat',
      'Ayyoub Bouaddi',
      'Neil El Aynaoui',
      'Bilal El Khannouss',
      'Samir El Mourabet',
      'Azzedine Ounahi',
      'Ismael Saibari',
    ],
    forwards: [
      'Ayoube Amaimouni',
      'Brahim Diaz',
      'Ayoub El Kaabi',
      'Abdessamad Ezzalzouli',
      'Yassine Gessime',
      'Soufiane Rahimi',
      'Chemsdine Talbi',
    ],
  ),
  'Netherlands': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Mark Flekken', 'Robin Roefs', 'Bart Verbruggen'],
    defenders: [
      'Nathan Ake',
      'Denzel Dumfries',
      'Jorrel Hato',
      'Lutsharel Geertruida',
      'Micky van de Ven',
      'Virgil van Dijk',
      'Jan Paul van Hecke',
    ],
    midfielders: [
      'Frenkie de Jong',
      'Marten de Roon',
      'Ryan Gravenberch',
      'Justin Kluivert',
      'Teun Koopmeiners',
      'Tijjani Reijnders',
      'Guus Til',
      'Quinten Timber',
      'Mats Wieffer',
    ],
    forwards: [
      'Brian Brobbey',
      'Memphis Depay',
      'Cody Gakpo',
      'Noa Lang',
      'Donyell Malen',
      'Crysencio Summerville',
      'Wout Weghorst',
    ],
  ),
  'New Zealand': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Max Crocombe', 'Alex Paulsen', 'Michael Woud'],
    defenders: [
      'Tim Payne',
      'Francis De Vries',
      'Tyler Bindon',
      'Michael Boxall',
      'Liberato Cacace',
      'Nando Pijnaker',
      'Finn Surman',
      'Callan Elliot',
      'Tommy Smith',
    ],
    midfielders: [
      'Joe Bell',
      'Marko Stamenic',
      'Alex Rufer',
      'Ryan Thomas',
      'Lachlan Bayliss',
    ],
    forwards: [
      'Matt Garbett',
      'Chris Wood',
      'Sarpreet Singh',
      'Eli Just',
      'Kosta Barbarouses',
      'Ben Waine',
      'Ben Old',
      'Callum McCowatt',
      'Jesse Randall',
    ],
  ),
  'Norway': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Orjan Haskjold Nyland', 'Egil Selvik', 'Sander Tangvik'],
    defenders: [
      'Julian Ryerson',
      'Marcus Holmgren Pedersen',
      'David Moller Wolfe',
      'Fredrik Bjorkan',
      'Kristoffer Ajer',
      'Torbjorn Heggem',
      'Leo Skiri Ostigard',
      'Sondre Langas',
      'Henrik Falchener',
    ],
    midfielders: [
      'Martin Odegaard',
      'Sander Berge',
      'Fredrik Aursnes',
      'Patrick Berg',
      'Kristian Thorstvedt',
      'Morten Thorsby',
      'Thelo Aasgaard',
    ],
    forwards: [
      'Erling Haaland',
      'Alexander Sorloth',
      'Jorgen Strand Larsen',
      'Antonio Nusa',
      'Oscar Bobb',
      'Andreas Schjelderup',
      'Jens Petter Hauge',
    ],
  ),
  'Panama': WorldCupRosterPool(
    formation: '3-4-3',
    goalkeepers: ['Orlando Mosquera', 'Luis Mejia', 'Cesar Samudio'],
    defenders: [
      'Cesar Blackman',
      'Jorge Gutierrez',
      'Amir Murillo',
      'Fidel Escobar',
      'Andres Andrade',
      'Edgardo Farina',
      'Jose Cordoba',
      'Eric Davis',
      'Jiovany Ramos',
      'Roderick Miller',
    ],
    midfielders: [
      'Anibal Godoy',
      'Adalberto Carrasquilla',
      'Carlos Harvey',
      'Cristian Martinez',
      'Jose Luis Rodriguez',
      'Cesar Yanis',
      'Yoel Barcenas',
      'Alberto Quintero',
      'Azarias Londono',
    ],
    forwards: [
      'Ismael Diaz',
      'Cecilio Waterman',
      'Jose Fajardo',
      'Tomas Rodriguez',
    ],
  ),
  'Paraguay': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Roberto Junior Fernandez', 'Orlando Gill', 'Gaston Olveira'],
    defenders: [
      'Omar Alderete',
      'Junior Alonso',
      'Fabian Balbuena',
      'Juan Jose Caceres',
      'Jose Canale',
      'Gustavo Gomez',
      'Alexandro Maidana',
      'Gustavo Velazquez',
    ],
    midfielders: [
      'Damian Bobadilla',
      'Gustavo Caballero',
      'Andres Cubas',
      'Matias Galarza',
      'Diego Gomez',
      'Mauricio Magalhaes',
      'Briaian Ojeda',
      'Alejandro Romero',
    ],
    forwards: [
      'Miguel Almiron',
      'Gabriel Avalos',
      'Alex Arce',
      'Julio Enciso',
      'Isidro Pitta',
      'Antonio Sanabria',
      'Ramon Sosa',
    ],
  ),
  'Portugal': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Diogo Costa', 'Jose Sa', 'Rui Silva'],
    defenders: [
      'Diogo Dalot',
      'Matheus Nunes',
      'Ruben Dias',
      'Nelson Semedo',
      'Joao Cancelo',
      'Nuno Mendes',
      'Goncalo Inacio',
      'Renato Veiga',
      'Tomas Araujo',
    ],
    midfielders: [
      'Ruben Neves',
      'Samu Costa',
      'Joao Neves',
      'Vitinha',
      'Bruno Fernandes',
      'Bernardo Silva',
    ],
    forwards: [
      'Cristiano Ronaldo',
      'Joao Felix',
      'Francisco Trincao',
      'Francisco Conceicao',
      'Pedro Neto',
      'Rafael Leao',
      'Goncalo Guedes',
      'Goncalo Ramos',
    ],
  ),
  'Qatar': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Salah Zakaria', 'Mahmoud Abunada', 'Meshaal Barsham'],
    defenders: [
      'Hashmi Hussein',
      'Ayoub Alawi',
      'Boualem Khoukhi',
      'Pedro Miguel',
      'Issa Laaye',
      'Lucas Mendes',
      'Sultan Al-Brake',
      'Homam Al-Amin',
    ],
    midfielders: [
      'Mohammed Al-Manai',
      'Jassem Jaber',
      'Karim Boudiaf',
      'Ahmed Fathi',
      'Abdulaziz Hatem',
      'Assim Madibo',
    ],
    forwards: [
      'Tahseen Mohammed',
      'Edmilson Junior',
      'Almoez Ali',
      'Akram Afif',
      'Mohammed Muntari',
      'Youssef Abdulrazzaq',
      'Ahmed Alaa',
      'Hassan Al-Haydos',
      'Ahmed Al-Janahi',
    ],
  ),
  'Saudi Arabia': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Mohammed Al-Owais', 'Nawaf Al-Aqidi', 'Ahmed Al-Kassar'],
    defenders: [
      'Abdulelah Al-Amri',
      'Hassan Tambakti',
      'Jehad Thikri',
      'Ali Lajami',
      'Hassan Kadesh',
      'Saud Abdulhamid',
      'Mohammed Abu Al-Shamat',
      'Ali Majrashi',
      'Moteb Al-Harbi',
      'Nawaf Boushal',
      'Sultan Al-Ghannam',
    ],
    midfielders: [
      'Mohammed Kanno',
      'Abdullah Al-Khaibari',
      'Ziyad Al-Johani',
      'Nasser Al-Dawsari',
      'Musab Al-Juwayr',
      'Alaa Al-Hajji',
      'Salem Al-Dawsari',
      'Khalid Al-Ghannam',
      'Ayman Yahya',
    ],
    forwards: ['Firas Al-Buraikan', 'Saleh Al-Shehri', 'Abdullah Al-Hamdan'],
  ),
  'Scotland': WorldCupRosterPool(
    formation: '4-4-2',
    goalkeepers: ['Craig Gordon', 'Angus Gunn', 'Liam Kelly'],
    defenders: [
      'Grant Hanley',
      'Jack Hendry',
      'Aaron Hickey',
      'Dom Hyam',
      'Scott McKenna',
      'Nathan Patterson',
      'Anthony Ralston',
      'Andy Robertson',
      'John Souttar',
      'Kieran Tierney',
    ],
    midfielders: [
      'Ryan Christie',
      'Finlay Curtis',
      'Lewis Ferguson',
      'Ben Gannon-Doak',
      'Tyler Fletcher',
      'John McGinn',
      'Kenny McLean',
      'Scott McTominay',
    ],
    forwards: [
      'Che Adams',
      'Lyndon Dykes',
      'George Hirst',
      'Lawrence Shankland',
      'Ross Stewart',
    ],
  ),
  'Senegal': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Edouard Mendy', 'Yehvann Diouf', 'Mory Diaw'],
    defenders: [
      'Krepin Diatta',
      'Antoine Mendy',
      'Abdoulaye Seck',
      'Kalidou Koulibaly',
      'Moussa Niakhate',
      'Mamadou Sarr',
      'El-Hadji Malick Diouf',
      'Ismail Jakobs',
    ],
    midfielders: [
      'Idrissa Gueye',
      'Habib Diarra',
      'Pape Matar Sarr',
      'Pape Gueye',
      'Lamine Camara',
      'Pathe Ciss',
      'Bara Ndiaye',
    ],
    forwards: [
      'Sadio Mane',
      'Bamba Dieng',
      'Iliman Ndiaye',
      'Nicolas Jackson',
      'Assane Diao',
      'Ibrahim Mbaye',
      'Cherif Ndiaye',
      'Ismaila Sarr',
    ],
  ),
  'South Africa': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Ronwen Williams', 'Ricardo Goss', 'Sipho Chaine'],
    defenders: [
      'Khuliso Mudau',
      'Aubrey Modiba',
      'Khulumani Ndamane',
      'Olwethu Makhanya',
      'Bradley Cross',
      'Thabang Matuludi',
      'Nkosinathi Sibisi',
      'Kamogelo Sebelebele',
      'Ime Okon',
      'Samukele Kabini',
      'Mbekezeli Mbokazi',
    ],
    midfielders: [
      'Teboho Mokoena',
      'Jayden Adams',
      'Thalente Mbatha',
      'Sphephelo Sithole',
    ],
    forwards: [
      'Oswin Appollis',
      'Tshepang Moremi',
      'Evidence Makgopa',
      'Relebohile Mofokeng',
      'Lyle Foster',
      'Iqraam Rayners',
      'Themba Zwane',
      'Thapelo Maseko',
    ],
  ),
  'Spain': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Unai Simon', 'David Raya', 'Joan Garcia'],
    defenders: [
      'Pedro Porro',
      'Marcos Llorente',
      'Pau Cubarsi',
      'Marc Pubill',
      'Aymeric Laporte',
      'Eric Garcia',
      'Alejandro Grimaldo',
      'Marc Cucurella',
    ],
    midfielders: [
      'Rodri',
      'Martin Zubimendi',
      'Gavi',
      'Dani Olmo',
      'Pedri',
      'Fabian Ruiz',
      'Mikel Merino',
      'Alex Baena',
    ],
    forwards: [
      'Lamine Yamal',
      'Ferran Torres',
      'Yeremy Pino',
      'Nico Williams',
      'Victor Munoz',
      'Mikel Oyarzabal',
      'Borja Iglesias',
    ],
  ),
  'Sweden': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: [
      'Kristoffer Nordfeldt',
      'Viktor Johansson',
      'Jacob Widell Zetterstrom',
    ],
    defenders: [
      'Daniel Svensson',
      'Victor Lindelof',
      'Isak Hien',
      'Carl Starfelt',
      'Elliot Stroud',
      'Gustaf Lagerbielke',
      'Gabriel Gudmundsson',
      'Herman Johansson',
      'Hjalmar Ekdal',
      'Erik Smith',
    ],
    midfielders: [
      'Taha Ali',
      'Yasin Ayari',
      'Lucas Bergvall',
      'Jesper Karlstrom',
      'Mattias Svanberg',
      'Besfort Zeneli',
    ],
    forwards: [
      'Anthony Elanga',
      'Viktor Gyokeres',
      'Gustaf Nilsson',
      'Benjamin Nygren',
      'Alexander Isak',
      'Alexander Bernhardsson',
      'Ken Sema',
    ],
  ),
  'Switzerland': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Marvin Keller', 'Gregor Kobel', 'Yvon Mvogo'],
    defenders: [
      'Manuel Akanji',
      'Aurele Amenda',
      'Eray Comert',
      'Nico Elvedi',
      'Luca Jaquez',
      'Miro Muheim',
      'Ricardo Rodriguez',
      'Silvan Widmer',
    ],
    midfielders: [
      'Michel Aebischer',
      'Christian Fassnacht',
      'Remo Freuler',
      'Ardon Jashari',
      'Johan Manzambi',
      'Fabian Rieder',
      'Djibril Sow',
      'Ruben Vargas',
      'Granit Xhaka',
      'Denis Zakaria',
    ],
    forwards: [
      'Zeki Amdouni',
      'Breel Embolo',
      'Cedric Itten',
      'Dan Ndoye',
      'Noah Okafor',
    ],
  ),
  'Tunisia': WorldCupRosterPool(
    formation: '4-3-3',
    goalkeepers: ['Sabri Ben Hessen', 'Abdelmouhib Chamakh', 'Aymen Dahman'],
    defenders: [
      'Ali Abdi',
      'Adem Arous',
      'Mohamed Amine Ben Hamida',
      'Dylan Bronn',
      'Raed Chikhaoui',
      'Moutaz Neffati',
      'Omar Rekik',
      'Montassar Talbi',
      'Yan Valery',
    ],
    midfielders: [
      'Mortadha Ben Ouanes',
      'Anis Ben Slimane',
      'Ismael Gharbi',
      'Rani Khedira',
      'Mohamed Hadj Mahmoud',
      'Hannibal Mejbri',
      'Ellyes Skhiri',
    ],
    forwards: [
      'Elias Achouri',
      'Khalil Ayari',
      'Firas Chaouat',
      'Rayan Elloumi',
      'Hazem Mastouri',
      'Elias Saad',
      'Sebastian Tounekti',
    ],
  ),
  'Turkiye': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Altay Bayindir', 'Mert Gunok', 'Ugurcan Cakir'],
    defenders: [
      'Abdulkerim Bardakci',
      'Caglar Soyuncu',
      'Eren Elmali',
      'Ferdi Kadioglu',
      'Merih Demiral',
      'Mert Muldur',
      'Ozan Kabak',
      'Samet Akaydin',
      'Zeki Celik',
    ],
    midfielders: [
      'Hakan Calhanoglu',
      'Ismail Yuksek',
      'Kaan Ayhan',
      'Orkun Kokcu',
      'Salih Ozcan',
    ],
    forwards: [
      'Arda Guler',
      'Baris Alper Yilmaz',
      'Can Uzun',
      'Deniz Gul',
      'Irfan Can Kahveci',
      'Kenan Yildiz',
      'Kerem Akturkoglu',
      'Oguz Aydin',
      'Yunus Akgun',
    ],
  ),
  'USA': WorldCupRosterPool(
    formation: '3-4-3',
    goalkeepers: ['Chris Brady', 'Matt Freese', 'Matt Turner'],
    defenders: [
      'Max Arfsten',
      'Sergino Dest',
      'Alex Freeman',
      'Mark McKenzie',
      'Tim Ream',
      'Chris Richards',
      'Antonee Robinson',
      'Miles Robinson',
      'Joe Scally',
      'Auston Trusty',
    ],
    midfielders: [
      'Tyler Adams',
      'Sebastian Berhalter',
      'Weston McKennie',
      'Cristian Roldan',
      'Brenden Aaronson',
      'Christian Pulisic',
      'Gio Reyna',
      'Malik Tillman',
      'Tim Weah',
      'Alejandro Zendejas',
    ],
    forwards: ['Folarin Balogun', 'Ricardo Pepi', 'Haji Wright'],
  ),
  'Uruguay': WorldCupRosterPool(
    formation: '4-2-3-1',
    goalkeepers: ['Sergio Rochet', 'Fernando Muslera', 'Santiago Mele'],
    defenders: [
      'Guillermo Varela',
      'Ronald Araujo',
      'Jose Maria Gimenez',
      'Santiago Bueno',
      'Sebastian Caceres',
      'Mathias Olivera',
      'Joaquin Piquerez',
      'Matias Vina',
    ],
    midfielders: [
      'Manuel Ugarte',
      'Emiliano Martinez',
      'Rodrigo Bentancur',
      'Federico Valverde',
      'Agustin Canobbio',
      'Juan Manuel Sanabria',
      'Giorgian de Arrascaeta',
      'Nicolas de la Cruz',
      'Rodrigo Zalazar',
      'Facundo Pellistri',
      'Maximiliano Araujo',
      'Brian Rodriguez',
    ],
    forwards: ['Rodrigo Aguirre', 'Federico Vinas', 'Darwin Nunez'],
  ),
  'Uzbekistan': WorldCupRosterPool(
    formation: '5-2-3',
    goalkeepers: ['Utkir Yusupov', 'Abduvohid Nematov', 'Botirali Ergashev'],
    defenders: [
      'Rustam Ashurmatov',
      'Farrukh Sayfiev',
      'Khojiakbar Alijonov',
      'Sherzod Nasrullaev',
      'Umar Eshmurodov',
      'Abdukodir Khusanov',
      'Abdulla Abdullaev',
      'Bekhruz Karimov',
      'Jakhongir Urozov',
      'Avazbek Ulmasaliev',
    ],
    midfielders: [
      'Otabek Shukurov',
      'Jaloliddin Masharipov',
      'Odiljon Hamrobekov',
      'Oston Urunov',
      'Jamshid Iskanderov',
      'Dostonbek Khamdamov',
      'Abbosbek Fayzullaev',
      'Akmal Mozgovoy',
      'Azizjon Ganiev',
      'Sherzod Esanov',
    ],
    forwards: ['Eldor Shomurodov', 'Igor Sergeev', 'Azizbek Amonov'],
  ),
};
