#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

API = "https://api.github.com"


def env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise RuntimeError(f"Missing env: {name}")
    return value


def request(method: str, url: str, token: str, payload: dict | None = None) -> dict | list:
    data = None
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = resp.read().decode("utf-8")
            return json.loads(body) if body else {}
    except urllib.error.HTTPError as exc:
        msg = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"API {method} {url} failed ({exc.code}): {msg}") from exc


def post_issue_comment(repo: str, issue_number: int, token: str, body: str) -> None:
    request(
        "POST",
        f"{API}/repos/{repo}/issues/{issue_number}/comments",
        token,
        {"body": body},
    )


def main() -> int:
    token = env("GITHUB_TOKEN")
    repo = env("GITHUB_REPOSITORY")
    issue_number = int(env("ISSUE_NUMBER"))
    issue_title = env("ISSUE_TITLE")
    branch = env("HEAD_BRANCH")
    base_branch = os.environ.get("BASE_BRANCH", "main")
    auto_merge = os.environ.get("AUTO_MERGE", "1").strip() == "1"
    merge_method = os.environ.get("AUTO_MERGE_METHOD", "squash").strip() or "squash"

    owner = repo.split("/", 1)[0]
    head_q = urllib.parse.urlencode({"state": "open", "head": f"{owner}:{branch}", "base": base_branch})
    existing = request("GET", f"{API}/repos/{repo}/pulls?{head_q}", token)
    if not isinstance(existing, list):
        raise RuntimeError("Unexpected PR query payload")

    pr_number: int | None = None
    if existing:
        pr = existing[0]
        pr_url = pr.get("html_url", "")
        pr_number = int(pr.get("number", 0) or 0)
    else:
        title = f"Auto: {issue_title} (#{issue_number})"
        body = (
            f"Automated implementation for #{issue_number}.\n\n"
            f"Closes #{issue_number}.\n\n"
            "Generated by local Codex worker via self-hosted GitHub Actions runner."
        )
        try:
            created = request(
                "POST",
                f"{API}/repos/{repo}/pulls",
                token,
                {
                    "title": title,
                    "head": branch,
                    "base": base_branch,
                    "body": body,
                },
            )
            if not isinstance(created, dict):
                raise RuntimeError("Unexpected PR creation payload")
            pr_url = created.get("html_url", "")
            pr_number = int(created.get("number", 0) or 0)
        except RuntimeError as exc:
            text = str(exc)
            manual_pr_url = (
                f"https://github.com/{repo}/pull/new/"
                f"{urllib.parse.quote(branch, safe='')}"
            )
            if "not permitted to create or approve pull requests" in text:
                post_issue_comment(
                    repo,
                    issue_number,
                    token,
                    (
                        "자동 작업 브랜치 푸시는 완료됐지만, 저장소 설정으로 인해 "
                        "GitHub Actions가 PR을 자동 생성하지 못했습니다.\n\n"
                        f"수동 PR 생성 링크: {manual_pr_url}"
                    ),
                )
                print(manual_pr_url)
                return 0
            raise

    if pr_url:
        post_issue_comment(repo, issue_number, token, f"자동 작업 브랜치 PR이 준비되었습니다: {pr_url}")

    if auto_merge and pr_number:
        try:
            merged = request(
                "PUT",
                f"{API}/repos/{repo}/pulls/{pr_number}/merge",
                token,
                {
                    "merge_method": merge_method,
                    "commit_title": f"Auto-merge: {issue_title} (#{issue_number})",
                },
            )
            if isinstance(merged, dict) and merged.get("merged") is True:
                post_issue_comment(
                    repo,
                    issue_number,
                    token,
                    f"자동 머지 완료: PR #{pr_number} ({merge_method})",
                )
            else:
                post_issue_comment(
                    repo,
                    issue_number,
                    token,
                    f"PR #{pr_number} 자동 머지를 시도했지만 완료되지 않았습니다. 응답: `{merged}`",
                )
        except RuntimeError as exc:
            post_issue_comment(
                repo,
                issue_number,
                token,
                f"PR #{pr_number} 자동 머지 실패: `{exc}`",
            )

    print(pr_url)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"[create_or_update_pr] ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
