#!/usr/bin/env python3
"""Sync open GitHub issues into docs/ISSUE_QUEUE.md.

Environment variables:
- GITHUB_REPOSITORY (required): owner/repo
- GITHUB_TOKEN (required): token with issues:read and contents:write
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone

API = "https://api.github.com"
OUTPUT = "docs/ISSUE_QUEUE.md"
MAX_ITEMS = 80


def _env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise RuntimeError(f"Missing environment variable: {name}")
    return value


def _request(url: str, token: str) -> list[dict]:
    req = urllib.request.Request(url)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = resp.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub API failed ({exc.code}): {body}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Network error: {exc}") from exc
    payload = json.loads(data)
    if not isinstance(payload, list):
        raise RuntimeError(f"Unexpected payload: {type(payload)}")
    return payload


def _load_issues(repo: str, token: str) -> list[dict]:
    q = urllib.parse.urlencode(
        {
            "state": "open",
            "per_page": "100",
            "sort": "updated",
            "direction": "desc",
        }
    )
    url = f"{API}/repos/{repo}/issues?{q}"
    issues = _request(url, token)
    filtered = [i for i in issues if "pull_request" not in i]
    return filtered[:MAX_ITEMS]


def _score(issue: dict) -> tuple[int, float, int]:
    labels = {lbl.get("name", "").lower() for lbl in issue.get("labels", [])}
    priority = 0
    if "priority:high" in labels or "p0" in labels:
        priority = 4
    elif "priority:medium" in labels or "p1" in labels:
        priority = 3
    elif "bug" in labels:
        priority = 2
    elif "enhancement" in labels:
        priority = 1

    updated = issue.get("updated_at", "")
    try:
        dt = datetime.fromisoformat(updated.replace("Z", "+00:00"))
        updated_ts = dt.timestamp()
    except ValueError:
        updated_ts = 0.0

    number = int(issue.get("number", 0))
    return (priority, updated_ts, -number)


def _fmt_issue(issue: dict) -> str:
    number = issue.get("number")
    title = str(issue.get("title", "")).strip()
    html_url = issue.get("html_url", "")
    labels = [lbl.get("name", "") for lbl in issue.get("labels", [])]
    labels_txt = ", ".join([x for x in labels if x])
    assignees = [a.get("login", "") for a in issue.get("assignees", [])]
    assignees_txt = ", ".join([x for x in assignees if x]) or "unassigned"
    updated = issue.get("updated_at", "")
    try:
        dt = datetime.fromisoformat(updated.replace("Z", "+00:00")).astimezone(timezone.utc)
        updated_txt = dt.strftime("%Y-%m-%d %H:%M UTC")
    except ValueError:
        updated_txt = updated

    extra = []
    if labels_txt:
        extra.append(f"labels: {labels_txt}")
    extra.append(f"owner: {assignees_txt}")
    extra.append(f"updated: {updated_txt}")
    meta = " | ".join(extra)
    return f"- [ ] #{number} [{title}]({html_url}) ({meta})"


def _render(repo: str, issues: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    prioritized = sorted(issues, key=_score, reverse=True)

    lines = [
        "# Issue Queue",
        "",
        f"Repository: `{repo}`",
        f"Last sync: `{now}`",
        "",
        "Auto-generated by `.github/workflows/issue-queue-sync.yml`.",
        "Do not edit manually.",
        "",
        "## Next Candidates",
        "",
    ]

    if not prioritized:
        lines.append("- No open issues.")
    else:
        for issue in prioritized[:20]:
            lines.append(_fmt_issue(issue))

    lines += ["", "## Backlog", ""]
    if len(prioritized) <= 20:
        lines.append("- No additional backlog issues.")
    else:
        for issue in prioritized[20:]:
            lines.append(_fmt_issue(issue))

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    try:
        repo = _env("GITHUB_REPOSITORY")
        token = _env("GITHUB_TOKEN")
        issues = _load_issues(repo, token)
        content = _render(repo, issues)
        with open(OUTPUT, "w", encoding="utf-8") as fh:
            fh.write(content)
    except Exception as exc:  # pragma: no cover
        print(f"[sync_issue_queue] ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"[sync_issue_queue] wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
